/**
 * Client-side exporters for all 4 tool result types.
 *
 * Output formats:
 *   - JSON  (.json)         raw structured payload
 *   - CSV   (.csv)          flat single-sheet for spreadsheets
 *   - MD    (.md)           human-readable Markdown
 *   - XLSX  (.xlsx)         multi-sheet Excel workbook (dynamic import)
 *
 * The XLSX path uses a dynamic import so `exceljs` (~700KB) only loads when
 * the user actually clicks "Export to Excel" — initial bundle stays small.
 */

import type {
  EdgeCaseList,
  ExploratoryChecklist,
  PlaywrightScript,
  TestCaseSuite,
  TestCoverageReport,
} from "@/lib/schemas";

export type ExportFormat = "xlsx" | "csv" | "md" | "json";

export type ToolSlug =
  | "analyze"
  | "edge-cases"
  | "exploratory"
  | "playwright"
  | "test-cases";

export const FORMAT_META: Record<ExportFormat, { label: string; ext: string; mime: string }> = {
  xlsx: {
    label: "Excel (.xlsx)",
    ext: "xlsx",
    mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  },
  csv: { label: "CSV (.csv)", ext: "csv", mime: "text/csv;charset=utf-8" },
  md: { label: "Markdown (.md)", ext: "md", mime: "text/markdown;charset=utf-8" },
  json: { label: "JSON (.json)", ext: "json", mime: "application/json" },
};

/* ----------------------- public API ----------------------- */

export async function exportResult(
  tool: ToolSlug,
  format: ExportFormat,
  data: unknown
): Promise<void> {
  const filename = buildFilename(tool, format);

  if (format === "json") {
    downloadBlob(filename, JSON.stringify(data, null, 2), FORMAT_META.json.mime);
    return;
  }

  if (format === "md") {
    const md = toMarkdown(tool, data);
    downloadBlob(filename, md, FORMAT_META.md.mime);
    return;
  }

  if (format === "csv") {
    const csv = toCsv(tool, data);
    downloadBlob(filename, csv, FORMAT_META.csv.mime);
    return;
  }

  if (format === "xlsx") {
    const blob = await toXlsxBlob(tool, data);
    triggerBlobDownload(filename, blob);
    return;
  }
}

/* ----------------------- filename / download helpers ----------------------- */

function buildFilename(tool: ToolSlug, format: ExportFormat): string {
  const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  return `qa-copilot-${tool}-${ts}.${FORMAT_META[format].ext}`;
}

function downloadBlob(filename: string, body: string, mime: string): void {
  triggerBlobDownload(filename, new Blob([body], { type: mime }));
}

function triggerBlobDownload(filename: string, blob: Blob): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/* ----------------------- CSV helpers ----------------------- */

function csvEscape(value: unknown): string {
  if (value === null || value === undefined) return "";
  const s = Array.isArray(value) ? value.join(" | ") : String(value);
  // Per RFC 4180: wrap in quotes if contains ", ',', newline. Double internal quotes.
  if (/[",\r\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function csvRows(rows: (string | number | string[])[][]): string {
  return rows.map((r) => r.map(csvEscape).join(",")).join("\r\n");
}

/* ----------------------- Markdown helpers ----------------------- */

function mdEscape(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function mdTable(headers: string[], rows: (string | number)[][]): string {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((r) => `| ${r.map((c) => mdEscape(String(c))).join(" | ")} |`).join("\n");
  return [head, sep, body].join("\n");
}

/* ----------------------- per-tool: MARKDOWN ----------------------- */

function toMarkdown(tool: ToolSlug, data: unknown): string {
  switch (tool) {
    case "analyze":
      return analyzeToMd(data as TestCoverageReport);
    case "edge-cases":
      return edgeCasesToMd(data as EdgeCaseList);
    case "exploratory":
      return exploratoryToMd(data as ExploratoryChecklist);
    case "playwright":
      return playwrightToMd(data as PlaywrightScript);
    case "test-cases":
      return testCasesToMd(data as TestCaseSuite);
  }
}

function analyzeToMd(d: TestCoverageReport): string {
  const lines: string[] = [];
  lines.push(`# QA Coverage Report`);
  lines.push(`> Generated by QA Copilot · ${new Date().toLocaleString()}`);
  lines.push("");
  lines.push(`**Coverage score:** ${d.coverage_score} / 100`);
  lines.push("");
  lines.push(`## Executive summary`);
  lines.push(d.summary);
  lines.push("");
  lines.push(`## Missing scenarios (${d.missing_scenarios.length})`);
  d.missing_scenarios.forEach((m, i) => {
    lines.push(`### ${i + 1}. ${m.scenario}  \`${m.severity}\``);
    lines.push(`**Rationale:** ${m.rationale}`);
    if (m.suggested_test_steps?.length) {
      lines.push("");
      lines.push(`**Suggested steps:**`);
      m.suggested_test_steps.forEach((s, j) => lines.push(`${j + 1}. ${s}`));
    }
    lines.push("");
  });
  lines.push(`## Risks (${d.risks.length})`);
  lines.push(mdTable(["Area", "Severity", "Description"], d.risks.map((r) => [r.area, r.severity, r.description])));
  lines.push("");
  lines.push(`## Recommendations`);
  d.recommendations.forEach((r) => lines.push(`- ${r}`));
  lines.push("");
  lines.push(`## Already covered (${d.covered_scenarios.length})`);
  lines.push(mdTable(["Scenario", "Evidence"], d.covered_scenarios.map((c) => [c.scenario, c.evidence])));
  return lines.join("\n");
}

function edgeCasesToMd(d: EdgeCaseList): string {
  const lines: string[] = [];
  lines.push(`# Edge Cases (${d.edge_cases.length})`);
  lines.push(`> Generated by QA Copilot · ${new Date().toLocaleString()}`);
  lines.push("");
  d.edge_cases.forEach((ec) => {
    lines.push(`## ${ec.id} — ${ec.title}`);
    lines.push(`**Severity:** \`${ec.severity}\` · **Category:** \`${ec.category}\``);
    lines.push("");
    if (ec.preconditions?.length) {
      lines.push(`**Preconditions:**`);
      ec.preconditions.forEach((p) => lines.push(`- ${p}`));
      lines.push("");
    }
    lines.push(`**Steps:**`);
    ec.steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
    lines.push("");
    lines.push(`**Expected result:** ${ec.expected_result}`);
    lines.push("");
    lines.push(`**Rationale:** ${ec.rationale}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  });
  return lines.join("\n");
}

function exploratoryToMd(d: ExploratoryChecklist): string {
  const lines: string[] = [];
  lines.push(`# Exploratory Testing Plan`);
  lines.push(`> Generated by QA Copilot · ${new Date().toLocaleString()}`);
  if (d.persona) lines.push(`> **Persona:** ${d.persona}`);
  lines.push("");
  lines.push(`## Charters (${d.charters.length})`);
  d.charters.forEach((c, i) => {
    lines.push(`### ${i + 1}. ${c.title}  \`${c.time_box_minutes} min\``);
    lines.push(`**Objective:** ${c.objective}`);
    lines.push("");
    lines.push(`**Areas to explore:** ${c.areas_to_explore.join(", ")}`);
    lines.push(`**Heuristics:** ${c.heuristics.join(", ")}`);
    lines.push("");
  });
  lines.push(`## Checklist`);
  d.checklist.forEach((c) => {
    lines.push(`### ${c.area}`);
    c.items.forEach((it) => lines.push(`- [ ] ${it}`));
    lines.push("");
  });
  lines.push(`## Oracles`);
  d.oracles.forEach((o) => lines.push(`- ${o}`));
  return lines.join("\n");
}

function playwrightToMd(d: PlaywrightScript): string {
  const fence = d.language === "typescript" ? "ts" : "js";
  const lines: string[] = [];
  lines.push(`# Playwright Test Spec`);
  lines.push(`> Generated by QA Copilot · ${new Date().toLocaleString()}`);
  lines.push("");
  lines.push(`**Filename:** \`${d.filename}\`  ·  **Language:** \`${d.language}\``);
  lines.push("");
  lines.push(`## Install`);
  lines.push("```bash");
  d.install_commands.forEach((c) => lines.push(c));
  lines.push("```");
  lines.push("");
  lines.push(`## Run`);
  lines.push("```bash");
  d.run_commands.forEach((c) => lines.push(c));
  lines.push("```");
  lines.push("");
  lines.push(`## ${d.filename}`);
  lines.push("```" + fence);
  lines.push(d.code);
  lines.push("```");
  if (d.notes?.length) {
    lines.push("");
    lines.push(`## Notes`);
    d.notes.forEach((n) => lines.push(`- ${n}`));
  }
  return lines.join("\n");
}

/* ----------------------- per-tool: CSV ----------------------- */

function toCsv(tool: ToolSlug, data: unknown): string {
  switch (tool) {
    case "analyze":
      return analyzeToCsv(data as TestCoverageReport);
    case "edge-cases":
      return edgeCasesToCsv(data as EdgeCaseList);
    case "exploratory":
      return exploratoryToCsv(data as ExploratoryChecklist);
    case "playwright":
      return playwrightToCsv(data as PlaywrightScript);
    case "test-cases":
      return testCasesToCsv(data as TestCaseSuite);
  }
}

function analyzeToCsv(d: TestCoverageReport): string {
  // Flatten the report. Multi-section CSVs separate sections with a blank row
  // and a "# Section" marker — Excel/Sheets handle this gracefully.
  const rows: (string | number | string[])[][] = [];
  rows.push(["# COVERAGE SCORE", d.coverage_score]);
  rows.push(["# SUMMARY", d.summary]);
  rows.push([]);
  rows.push(["# MISSING SCENARIOS"]);
  rows.push(["Scenario", "Severity", "Rationale", "Suggested steps"]);
  d.missing_scenarios.forEach((m) =>
    rows.push([m.scenario, m.severity, m.rationale, m.suggested_test_steps ?? []])
  );
  rows.push([]);
  rows.push(["# RISKS"]);
  rows.push(["Area", "Severity", "Description"]);
  d.risks.forEach((r) => rows.push([r.area, r.severity, r.description]));
  rows.push([]);
  rows.push(["# RECOMMENDATIONS"]);
  rows.push(["#", "Recommendation"]);
  d.recommendations.forEach((r, i) => rows.push([i + 1, r]));
  rows.push([]);
  rows.push(["# COVERED SCENARIOS"]);
  rows.push(["Scenario", "Evidence"]);
  d.covered_scenarios.forEach((c) => rows.push([c.scenario, c.evidence]));
  return csvRows(rows);
}

function edgeCasesToCsv(d: EdgeCaseList): string {
  const rows: (string | number | string[])[][] = [
    ["ID", "Title", "Category", "Severity", "Preconditions", "Steps", "Expected result", "Rationale"],
    ...d.edge_cases.map((ec) => [
      ec.id,
      ec.title,
      ec.category,
      ec.severity,
      ec.preconditions ?? [],
      ec.steps.map((s, i) => `${i + 1}. ${s}`),
      ec.expected_result,
      ec.rationale,
    ]),
  ];
  return csvRows(rows);
}

function exploratoryToCsv(d: ExploratoryChecklist): string {
  const rows: (string | number | string[])[][] = [];
  if (d.persona) {
    rows.push(["# PERSONA", d.persona]);
    rows.push([]);
  }
  rows.push(["# CHARTERS"]);
  rows.push(["Title", "Objective", "Areas to explore", "Heuristics", "Time-box (min)"]);
  d.charters.forEach((c) =>
    rows.push([c.title, c.objective, c.areas_to_explore, c.heuristics, c.time_box_minutes])
  );
  rows.push([]);
  rows.push(["# CHECKLIST"]);
  rows.push(["Area", "Item"]);
  d.checklist.forEach((c) => c.items.forEach((it) => rows.push([c.area, it])));
  rows.push([]);
  rows.push(["# ORACLES"]);
  rows.push(["#", "Oracle"]);
  d.oracles.forEach((o, i) => rows.push([i + 1, o]));
  return csvRows(rows);
}

function playwrightToCsv(d: PlaywrightScript): string {
  // Playwright is code, not tabular data. We emit metadata so a spreadsheet
  // user still gets something useful; the actual .spec file is exported
  // separately via the "Download spec file" button.
  const rows: (string | number | string[])[][] = [
    ["Field", "Value"],
    ["Filename", d.filename],
    ["Language", d.language],
    ["Install commands", d.install_commands],
    ["Run commands", d.run_commands],
    ["Notes", d.notes ?? []],
    ["Lines of code", d.code.split("\n").length],
  ];
  return csvRows(rows);
}

/* ----------------------- per-tool: XLSX ----------------------- */

// Brand colors used as cell fills in the workbook header rows.
const COLORS = {
  primary: "FF8B5CF6",
  primaryFg: "FFFFFFFF",
  headerFg: "FFFAFAFA",
  headerBg: "FF18181C",
  zebra: "FF0F0F12",
  critical: "FFEF4444",
  high: "FFF97316",
  medium: "FFEAB308",
  low: "FF3B82F6",
  emerald: "FF10B981",
} as const;

async function toXlsxBlob(tool: ToolSlug, data: unknown): Promise<Blob> {
  // Dynamic import keeps exceljs out of the initial client bundle.
  const ExcelJS = (await import("exceljs")).default;
  const wb = new ExcelJS.Workbook();
  wb.creator = "QA Copilot";
  wb.created = new Date();

  switch (tool) {
    case "analyze":
      analyzeToXlsx(wb, data as TestCoverageReport);
      break;
    case "edge-cases":
      edgeCasesToXlsx(wb, data as EdgeCaseList);
      break;
    case "exploratory":
      exploratoryToXlsx(wb, data as ExploratoryChecklist);
      break;
    case "playwright":
      playwrightToXlsx(wb, data as PlaywrightScript);
      break;
    case "test-cases":
      testCasesToXlsx(wb, data as TestCaseSuite);
      break;
  }

  const buffer = await wb.xlsx.writeBuffer();
  return new Blob([buffer], { type: FORMAT_META.xlsx.mime });
}

type XlsxWorksheet = import("exceljs").Worksheet;
type XlsxRow = import("exceljs").Row;
type XlsxCell = import("exceljs").Cell;

function styleHeader(row: XlsxRow): void {
  row.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: COLORS.headerFg }, size: 11 };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: COLORS.headerBg } };
    cell.alignment = { vertical: "middle", horizontal: "left", wrapText: true };
    cell.border = {
      bottom: { style: "thin", color: { argb: "FF3F3F46" } },
    };
  });
  row.height = 24;
}

function styleZebra(sheet: XlsxWorksheet, startRow = 2): void {
  for (let i = startRow; i <= sheet.rowCount; i += 2) {
    const row = sheet.getRow(i);
    row.eachCell((cell) => {
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: COLORS.zebra } };
    });
  }
}

function styleAllText(sheet: XlsxWorksheet): void {
  sheet.eachRow((row) => {
    row.eachCell((cell) => {
      cell.alignment = { ...cell.alignment, vertical: "top", wrapText: true };
      if (!cell.font) cell.font = { size: 10, color: { argb: COLORS.headerFg } };
    });
  });
}

function severityCell(cell: XlsxCell, sev: string): void {
  const map: Record<string, string> = {
    critical: COLORS.critical,
    high: COLORS.high,
    medium: COLORS.medium,
    low: COLORS.low,
  };
  const argb = map[sev] ?? COLORS.low;
  cell.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 10 };
  cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb } };
  cell.alignment = { vertical: "middle", horizontal: "center" };
}

function setColumnWidths(sheet: XlsxWorksheet, widths: number[]): void {
  widths.forEach((w, i) => {
    sheet.getColumn(i + 1).width = w;
  });
}

function addSummarySheet(wb: import("exceljs").Workbook, kvs: [string, string | number][]): void {
  const sheet = wb.addWorksheet("Summary", {
    properties: { tabColor: { argb: COLORS.primary } },
  });
  sheet.addRow(["Field", "Value"]);
  styleHeader(sheet.getRow(1));
  kvs.forEach(([k, v]) => sheet.addRow([k, v]));
  setColumnWidths(sheet, [28, 80]);
  styleAllText(sheet);
}

function analyzeToXlsx(wb: import("exceljs").Workbook, d: TestCoverageReport): void {
  addSummarySheet(wb, [
    ["Tool", "Analyze Test Cases"],
    ["Generated at", new Date().toLocaleString()],
    ["Coverage score (0-100)", d.coverage_score],
    ["Covered scenarios", d.covered_scenarios.length],
    ["Missing scenarios", d.missing_scenarios.length],
    ["Risks", d.risks.length],
    ["Recommendations", d.recommendations.length],
    ["Executive summary", d.summary],
  ]);

  // Missing scenarios
  const missing = wb.addWorksheet("Missing Scenarios", {
    properties: { tabColor: { argb: COLORS.high } },
  });
  missing.addRow(["#", "Scenario", "Severity", "Rationale", "Suggested test steps"]);
  styleHeader(missing.getRow(1));
  d.missing_scenarios.forEach((m, i) => {
    const row = missing.addRow([
      i + 1,
      m.scenario,
      m.severity,
      m.rationale,
      (m.suggested_test_steps ?? []).map((s, j) => `${j + 1}. ${s}`).join("\n"),
    ]);
    severityCell(row.getCell(3), m.severity);
  });
  setColumnWidths(missing, [5, 40, 12, 50, 60]);
  styleAllText(missing);

  // Risks
  const risks = wb.addWorksheet("Risks", {
    properties: { tabColor: { argb: COLORS.critical } },
  });
  risks.addRow(["Area", "Severity", "Description"]);
  styleHeader(risks.getRow(1));
  d.risks.forEach((r) => {
    const row = risks.addRow([r.area, r.severity, r.description]);
    severityCell(row.getCell(2), r.severity);
  });
  setColumnWidths(risks, [22, 12, 70]);
  styleAllText(risks);

  // Recommendations
  const recos = wb.addWorksheet("Recommendations", {
    properties: { tabColor: { argb: COLORS.primary } },
  });
  recos.addRow(["#", "Recommendation"]);
  styleHeader(recos.getRow(1));
  d.recommendations.forEach((r, i) => recos.addRow([i + 1, r]));
  setColumnWidths(recos, [5, 90]);
  styleAllText(recos);
  styleZebra(recos);

  // Covered scenarios
  const covered = wb.addWorksheet("Covered Scenarios", {
    properties: { tabColor: { argb: COLORS.emerald } },
  });
  covered.addRow(["#", "Scenario", "Evidence"]);
  styleHeader(covered.getRow(1));
  d.covered_scenarios.forEach((c, i) => covered.addRow([i + 1, c.scenario, c.evidence]));
  setColumnWidths(covered, [5, 50, 50]);
  styleAllText(covered);
  styleZebra(covered);
}

function edgeCasesToXlsx(wb: import("exceljs").Workbook, d: EdgeCaseList): void {
  addSummarySheet(wb, [
    ["Tool", "Generate Edge Cases"],
    ["Generated at", new Date().toLocaleString()],
    ["Total edge cases", d.edge_cases.length],
    [
      "Categories",
      Array.from(new Set(d.edge_cases.map((e) => e.category))).join(", "),
    ],
  ]);

  const sheet = wb.addWorksheet("Edge Cases", {
    properties: { tabColor: { argb: COLORS.primary } },
    views: [{ state: "frozen", ySplit: 1 }],
  });
  sheet.addRow([
    "ID",
    "Title",
    "Category",
    "Severity",
    "Preconditions",
    "Steps",
    "Expected result",
    "Rationale",
  ]);
  styleHeader(sheet.getRow(1));
  sheet.autoFilter = { from: "A1", to: "H1" };

  d.edge_cases.forEach((ec) => {
    const row = sheet.addRow([
      ec.id,
      ec.title,
      ec.category,
      ec.severity,
      (ec.preconditions ?? []).map((p) => `• ${p}`).join("\n"),
      ec.steps.map((s, i) => `${i + 1}. ${s}`).join("\n"),
      ec.expected_result,
      ec.rationale,
    ]);
    severityCell(row.getCell(4), ec.severity);
  });
  setColumnWidths(sheet, [10, 36, 18, 12, 30, 50, 40, 40]);
  styleAllText(sheet);
}

function exploratoryToXlsx(
  wb: import("exceljs").Workbook,
  d: ExploratoryChecklist
): void {
  addSummarySheet(wb, [
    ["Tool", "Exploratory Checklist"],
    ["Generated at", new Date().toLocaleString()],
    ["Persona", d.persona ?? "(none)"],
    ["Charters", d.charters.length],
    ["Checklist areas", d.checklist.length],
    [
      "Total checklist items",
      d.checklist.reduce((sum, c) => sum + c.items.length, 0),
    ],
    ["Oracles", d.oracles.length],
  ]);

  const charters = wb.addWorksheet("Charters", {
    properties: { tabColor: { argb: COLORS.emerald } },
  });
  charters.addRow(["#", "Title", "Time-box (min)", "Objective", "Areas to explore", "Heuristics"]);
  styleHeader(charters.getRow(1));
  d.charters.forEach((c, i) =>
    charters.addRow([
      i + 1,
      c.title,
      c.time_box_minutes,
      c.objective,
      c.areas_to_explore.map((a) => `• ${a}`).join("\n"),
      c.heuristics.map((h) => `• ${h}`).join("\n"),
    ])
  );
  setColumnWidths(charters, [5, 32, 14, 50, 32, 30]);
  styleAllText(charters);

  const checklist = wb.addWorksheet("Checklist", {
    properties: { tabColor: { argb: COLORS.low } },
    views: [{ state: "frozen", ySplit: 1 }],
  });
  checklist.addRow(["Area", "Item", "Done"]);
  styleHeader(checklist.getRow(1));
  d.checklist.forEach((c) =>
    c.items.forEach((it) => checklist.addRow([c.area, it, ""]))
  );
  checklist.autoFilter = { from: "A1", to: "C1" };
  setColumnWidths(checklist, [22, 80, 8]);
  styleAllText(checklist);

  const oracles = wb.addWorksheet("Oracles", {
    properties: { tabColor: { argb: COLORS.primary } },
  });
  oracles.addRow(["#", "Oracle"]);
  styleHeader(oracles.getRow(1));
  d.oracles.forEach((o, i) => oracles.addRow([i + 1, o]));
  setColumnWidths(oracles, [5, 100]);
  styleAllText(oracles);
  styleZebra(oracles);
}

function playwrightToXlsx(
  wb: import("exceljs").Workbook,
  d: PlaywrightScript
): void {
  addSummarySheet(wb, [
    ["Tool", "Generate Playwright Tests"],
    ["Generated at", new Date().toLocaleString()],
    ["Filename", d.filename],
    ["Language", d.language],
    ["Lines of code", d.code.split("\n").length],
    ["Install commands", d.install_commands.join("\n")],
    ["Run commands", d.run_commands.join("\n")],
    ["Notes", (d.notes ?? []).map((n) => `• ${n}`).join("\n") || "(none)"],
  ]);

  const code = wb.addWorksheet("Source Code", {
    properties: { tabColor: { argb: COLORS.high } },
  });
  code.addRow(["Line", "Code"]);
  styleHeader(code.getRow(1));
  d.code.split("\n").forEach((line, i) => {
    const row = code.addRow([i + 1, line]);
    row.getCell(2).font = { name: "Consolas", size: 10, color: { argb: COLORS.headerFg } };
    row.getCell(1).font = { name: "Consolas", size: 9, color: { argb: "FF71717A" } };
  });
  setColumnWidths(code, [6, 140]);
}

/* ----------------------- test-cases: MARKDOWN ----------------------- */

function testCasesToMd(d: TestCaseSuite): string {
  const lines: string[] = [];
  lines.push(`# ${d.feature} — Test Case Suite`);
  lines.push(`> Generated by QA Copilot · ${new Date().toLocaleString()}`);
  lines.push("");
  lines.push(`**Total cases:** ${d.test_cases.length}`);
  lines.push("");
  lines.push(`## Summary`);
  lines.push(d.summary);
  lines.push("");

  const byType = groupBy(d.test_cases, (tc) => tc.type);
  Object.entries(byType)
    .sort(([a], [b]) => a.localeCompare(b))
    .forEach(([type, list]) => {
      lines.push(`## ${capitalize(type)} (${list.length})`);
      list.forEach((tc) => {
        lines.push("");
        lines.push(`### ${tc.id} — ${tc.title}  \`${tc.priority}\``);
        if (tc.preconditions?.length) {
          lines.push(`**Preconditions:**`);
          tc.preconditions.forEach((p) => lines.push(`- ${p}`));
        }
        lines.push(`**Steps:**`);
        tc.steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
        if (tc.test_data) lines.push(`**Test data:** \`${tc.test_data}\``);
        lines.push(`**Expected:** ${tc.expected_result}`);
        if (tc.tags?.length)
          lines.push(`**Tags:** ${tc.tags.map((t) => `\`${t}\``).join(" ")}`);
      });
      lines.push("");
    });

  if (d.coverage_notes?.length) {
    lines.push(`## Coverage notes`);
    d.coverage_notes.forEach((n) => lines.push(`- ${n}`));
  }
  return lines.join("\n");
}

/* ----------------------- test-cases: CSV ----------------------- */

/**
 * TMS-friendly flat CSV — one row per test case. Column order matches the
 * Excel "Test Cases" sheet so users can swap formats freely. Includes an
 * empty "Status" column so testers can fill Pass/Fail/Blocked after import.
 */
function testCasesToCsv(d: TestCaseSuite): string {
  const rows: (string | number | string[])[][] = [
    [
      "ID",
      "Title",
      "Type",
      "Priority",
      "Preconditions",
      "Steps",
      "Test Data",
      "Expected Result",
      "Tags",
      "Status",
    ],
    ...d.test_cases.map((tc) => [
      tc.id,
      tc.title,
      tc.type,
      tc.priority,
      tc.preconditions ?? [],
      tc.steps.map((s, i) => `${i + 1}. ${s}`),
      tc.test_data ?? "",
      tc.expected_result,
      tc.tags ?? [],
      "",
    ]),
  ];
  return csvRows(rows);
}

/* ----------------------- test-cases: XLSX ----------------------- */

function testCasesToXlsx(
  wb: import("exceljs").Workbook,
  d: TestCaseSuite
): void {
  const byType = groupBy(d.test_cases, (tc) => tc.type);
  const byPriority = groupBy(d.test_cases, (tc) => tc.priority);

  // Summary sheet — feature, counts, breakdown by type and priority
  addSummarySheet(wb, [
    ["Tool", "Test Case Suite"],
    ["Feature", d.feature],
    ["Generated at", new Date().toLocaleString()],
    ["Total cases", d.test_cases.length],
    ["Summary", d.summary],
    [
      "By type",
      Object.entries(byType)
        .map(([t, list]) => `${t}: ${list.length}`)
        .join("\n"),
    ],
    [
      "By priority",
      Object.entries(byPriority)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([p, list]) => `${p}: ${list.length}`)
        .join("\n"),
    ],
    [
      "Coverage notes",
      (d.coverage_notes ?? []).map((n) => `• ${n}`).join("\n") || "(none)",
    ],
  ]);

  // Main "Test Cases" sheet — flat, TMS-import-ready. Empty Status column
  // lets a tester fill Pass/Fail/Blocked without restructuring the sheet.
  const sheet = wb.addWorksheet("Test Cases", {
    properties: { tabColor: { argb: COLORS.primary } },
    views: [{ state: "frozen", ySplit: 1, xSplit: 1 }],
  });
  sheet.addRow([
    "ID",
    "Title",
    "Type",
    "Priority",
    "Preconditions",
    "Steps",
    "Test Data",
    "Expected Result",
    "Tags",
    "Status",
  ]);
  styleHeader(sheet.getRow(1));
  sheet.autoFilter = { from: "A1", to: "J1" };

  d.test_cases.forEach((tc) => {
    const row = sheet.addRow([
      tc.id,
      tc.title,
      tc.type,
      tc.priority,
      (tc.preconditions ?? []).map((p) => `• ${p}`).join("\n"),
      tc.steps.map((s, i) => `${i + 1}. ${s}`).join("\n"),
      tc.test_data ?? "",
      tc.expected_result,
      (tc.tags ?? []).join(", "),
      "",
    ]);
    priorityCell(row.getCell(4), tc.priority);
  });
  setColumnWidths(sheet, [10, 36, 14, 10, 28, 50, 24, 40, 22, 12]);
  styleAllText(sheet);

  // Status column data validation: dropdown of Pass/Fail/Blocked/N/A.
  // Lets the tester fill it after import without typing the value each time.
  for (let i = 2; i <= d.test_cases.length + 1; i++) {
    sheet.getCell(`J${i}`).dataValidation = {
      type: "list",
      allowBlank: true,
      formulae: ['"Not Run,Pass,Fail,Blocked,N/A"'],
      showErrorMessage: true,
      errorTitle: "Invalid status",
      error: "Status must be Pass, Fail, Blocked, N/A, or empty.",
    };
  }

  // Optional: per-type breakdown sheets for users that prefer drilldowns
  Object.entries(byType).forEach(([type, list]) => {
    const tab = wb.addWorksheet(`${capitalize(type)} (${list.length})`, {
      properties: { tabColor: { argb: COLORS.headerBg } },
      views: [{ state: "frozen", ySplit: 1 }],
    });
    tab.addRow(["ID", "Title", "Priority", "Steps", "Expected Result"]);
    styleHeader(tab.getRow(1));
    list.forEach((tc) => {
      const row = tab.addRow([
        tc.id,
        tc.title,
        tc.priority,
        tc.steps.map((s, i) => `${i + 1}. ${s}`).join("\n"),
        tc.expected_result,
      ]);
      priorityCell(row.getCell(3), tc.priority);
    });
    setColumnWidths(tab, [10, 40, 10, 60, 40]);
    styleAllText(tab);
  });
}

/** Color-code priority cells (P0=red … P3=blue). */
function priorityCell(cell: XlsxCell, priority: string): void {
  const map: Record<string, string> = {
    P0: COLORS.critical,
    P1: COLORS.high,
    P2: COLORS.medium,
    P3: COLORS.low,
  };
  const argb = map[priority] ?? COLORS.low;
  cell.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 10 };
  cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb } };
  cell.alignment = { vertical: "middle", horizontal: "center" };
}

/* ----------------------- tiny shared utilities ----------------------- */

function groupBy<T, K extends string>(
  arr: T[],
  key: (item: T) => K
): Record<K, T[]> {
  const out = {} as Record<K, T[]>;
  for (const item of arr) {
    const k = key(item);
    (out[k] ||= []).push(item);
  }
  return out;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
